type: object
title: StandaloneConfidenceIntervalConfig
description: Configuration for a standalone confidence interval computation.
allOf:
  - $ref: ./ConfidenceIntervalConfigCommon.yaml
  - type: object
    properties:
      results_data_ref:
        oneOf:
          - $ref: ./EvaluationJobDataRef.yaml
          - $ref: ./ExternalResultsDataRef.yaml
        description: Result data reference. An evaluation job is supported only for result data.
    required:
      - results_data_ref
unevaluatedProperties: false
