name: Bug report
description: Something isn't working
title: "fix: "
labels: ["kind/fix", "status/triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: What did you expect, and what happened instead?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - API
        - Executor (lm-evaluation-harness)
        - Executor (NeMo Evaluator)
        - Executor (Lighteval/KFP)
        - MLFlow integration
        - Deployment (Local/Podman/Kubernetes/OpenShift)
        - Configuration
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g. 0.1.0
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or errors
      render: shell
